### ISSUE TITLE
How to get the third person view as shown in your TASK.md?

### ISSUE THREAD

**Issue by gemcollector** [ir413/mvp#10]
Thanks for updating the code !! I wonder how to get the third person view as shown in your TASK.md? It seems that all the training are conducted in the egocentric view.

**Comment by ir413** [comment]
Hi @gemcollector! That's right, we us the egocentric view for all experiments. The third-person views you mention were generated only for visualization purposes by an additional camera in a pretty hacky way.

Will try to think if there's a clean way to integrate support for that. In the meantime, here are some code snippets that you can use/adapt to get the third-person images like shown in [`TASKS.md`](https://github.com/ir413/mvp/blob/master/TASKS.md):

Create a camera (e.g., in the `_create_envs` function like [here](https://github.com/ir413/mvp/blob/master/pixmc/tasks/franka_pick.py#L311)):

```
self.save_cam_env_ind = 29
save_cam_env = self.envs[self.save_cam_env_ind]
cam_props = gymapi.CameraProperties()
cam_props.width = 1920
cam_props.height = 1440
cam_props.horizontal_fov = 65
cam_props.supersampling_horizontal = 1
cam_props.supersampling_vertical = 1
cam_handle = self.gym.create_camera_sensor(save_cam_env, cam_props)
cam_pos = gymapi.Vec3(-0.1, 0.6, 1.1)
cam_target = gymapi.Vec3(0.5, 0.1, 0.6)
self.gym.set_camera_location(cam_handle, save_cam_env, cam_pos, cam_target)
self.save_cam = cam_handle
self.save_vis_ep = 0
```

Save camera image (e.g., at the end of `post_physics_step` function like [here](https://github.com/ir413/mvp/blob/master/pixmc/tasks/franka_pick.py#L479)):

```
i = self.save_cam_env_ind
j = self.progress_buf[i]
if j == 0:
    self.save_vis_ep += 1
ep = self.save_vis_ep
out_dir = "/path/to/out/dir"
out_name = "cam-%04d-%04d-%04d.png" % (ep, i, j)
out_f = os.path.join(out_dir, out_name)
self.gym.write_camera_image_to_file(self.sim, self.envs[i], self.save_cam, gymapi.IMAGE_COLOR, out_f)
```
