### ISSUE TITLE
hello, I wanna know how do you observe the action of the robots?

### ISSUE THREAD

**Issue by Patricia1019** [ir413/mvp#2]
hi, I am sorry to bother you but  I am new to reinforcement learning.
I have read your paper and I see you write in the paper that you use wrist-mounted cameras to capture the movements of the robots, I wonder what is the real meaning of wrist-mounted camera? Is it a default setting of the simulator, or is it a real camera in physical world?
Thank you : )

**Comment by ir413** [comment]
Hi @Patricia1019, by wrist-mounted camera we mean that the camera is attached to the robot's wrist and it follows its position in simulation. Please find a few example frames captured by the camera below:

![franka-wrist-ex1](https://user-images.githubusercontent.com/6415258/161448362-67190dc4-5d00-4361-8b7c-45a66188d915.png) ![franka-wrist-ex2](https://user-images.githubusercontent.com/6415258/161448369-5dbf6a4c-a265-4950-b672-e9621583b695.png) ![franka-wrist-ex3](https://user-images.githubusercontent.com/6415258/161448378-d85f6338-8f8c-4dac-aadc-332fb8adbb1f.png)

**Comment by Patricia1019** [comment]
got it ! Thank you !
