### ISSUE TITLE
About IsaacGym Preview 2

### ISSUE THREAD

**Issue by jasonseu** [ir413/mvp#6]
Hi, thanks for your awesome work. I am trying to reproduce your work by following the instructions in README. However, IsaacGym Preview 2 can not be accessed since its Preview 3 has been released in official website. So, would you please share the package of  IsaacGym Preview 2 with me? Thanks in advance.

**Comment by ir413** [comment]
Hi @jasonseu, sorry for the late response. I'm not sure if we are allowed to redistribute NVIDIA software per user agreement. However, several groups were able to reproduce the results using Preview 3 so you should be able to use that. If you really want to use Preview 2 instead, I suggest reaching out to NVIDIA and asking for access. Hope this helps!
