### ISSUE TITLE
Reset management for multiple envs

### ISSUE THREAD

**Issue by MathisClautrier** [ir413/mvp#7]
Hi, thanks for this project and making available your code,

I am playing with PixMc and your model for few days, but I still have a pending question,

In task/configs an episode length is specified whereas in mvp/ppo.py the environments are never reinitialized (apply_reset set to false). I am deducing that this is automatic. Similarly, I assume that when a given environment reaches a goal it is reinitialized automatically. Am I right to think so? And if not, how can I successfully reset the environment when the goal states are reached?

**Comment by ir413** [comment]
Hi @MathisClautrier, sorry for the late response. In case this is still useful: we use [`reset_buf`](https://github.com/ir413/mvp/blob/master/pixmc/tasks/franka_pick.py#L408) tensors to keep track of resets. The environments are reset when the [max episode length is exceeded](https://github.com/ir413/mvp/blob/master/pixmc/tasks/franka_pick.py#L541) or one of the other termination criteria is met (e.g., [arm collision](https://github.com/ir413/mvp/blob/master/pixmc/tasks/franka_pick.py#L538) or [object below the table](https://github.com/ir413/mvp/blob/master/pixmc/tasks/franka_pick.py#L534)). We do not reset the environments when the goal is reached. Hope this helps!
